/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PlContent: typeof import('./src/components/pl-content.vue')['default']
    PlDownload: typeof import('./src/components/pl-download.vue')['default']
    PlEditor: typeof import('./src/components/pl-editor.vue')['default']
    PlHeader: typeof import('./src/components/pl-header.vue')['default']
    PlIframe: typeof import('./src/components/pl-iframe.vue')['default']
    PlShare: typeof import('./src/components/pl-share.vue')['default']
    PlTour: typeof import('./src/components/pl-tour.vue')['default']
  }
}
